import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { projectRoot, basePath as configuredBase, origin as configuredOrigin } from './config.mjs';
import { pathToFileURL } from 'node:url';
import { validatePoems } from './validate.mjs';
export function buildSite({basePath=configuredBase, origin=configuredOrigin}={}) {
const publicUrl=route=>origin+basePath+'/'+route;
const root=path.join(projectRoot,'dist'), data=JSON.parse(fs.readFileSync(root+'/data.json','utf8'));
validatePoems(data);
const contentVersion=createHash('sha256').update(JSON.stringify(data)).update(fs.readFileSync(root+'/app.js')).update(fs.readFileSync(root+'/identity.css')).digest('hex').slice(0,12);
const generatedPoems=path.resolve(root,'poems');
if(generatedPoems.startsWith(path.resolve(root)+path.sep))fs.rmSync(generatedPoems,{recursive:true,force:true});
const poet='عبدالرحمن بن محمد آل شرعان الخيارين';
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const url=p=>'/poems/'+p.id+'/';
const sourceLabel=p=>p.source.type==='x'?'فيديو على X':p.source.type==='user'?'نص من صاحب المشروع':'البطاقة '+p.source.region;
const media=p=>p.source.type==='x'?`<section class="poem-video" aria-label="فيديو القصيدة"><h2>القصيدة في فيديو</h2><iframe loading="lazy" title="منشور فيديو ${e(p.title)}" src="https://platform.twitter.com/embed/Tweet.html?id=${encodeURIComponent(p.source.postId)}&dnt=true" allow="fullscreen" style="display:block;width:100%;max-width:550px;height:740px;border:0;margin:1rem auto"></iframe><p><a href="${e(p.source.url)}" target="_blank" rel="noopener noreferrer">مشاهدة الفيديو الأصلي على X ↗</a></p></section>`:'';
const badge=p=>`${p.status.includes('مراجعة')?'<span class="tag warn">يحتاج مراجعة</span>':''}`;
const card=p=>`<a class="poem-card" href="${url(p)}"><div class="card-top"><span class="ordinal">${(p.displayNumber ?? p.id.slice(1))}</span>${badge(p)}</div><h3>${e(p.title)}</h3><div class="excerpt">${(p.verses[0]||['النص محفوظ في صورة المصدر']).map(s=>`<span>${e(s)}</span>`).join('')}</div><div class="card-foot"><span>${p.verses.length} أبيات · ${e(sourceLabel(p))}</span><span>اقرأ القصيدة ←</span></div></a>`;
function page(route,title,description,content){const out=path.join(root,route,'index.html');fs.mkdirSync(path.dirname(out),{recursive:true});const html=`<!doctype html><html lang="ar" dir="rtl" data-base-path="${e(basePath)}" data-content-version="${contentVersion}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)} | ديوان بن شرعان</title><meta name="description" content="${e(description)}"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(description)}"><meta property="og:type" content="${route.startsWith('poems/')?'article':'website'}"><meta property="og:url" content="${e(publicUrl(route+(route?'/':'')))}"><link rel="canonical" href="${e(publicUrl(route+(route?'/':'')))}"><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/identity.css?v=${contentVersion}"><script src="/app.js?v=${contentVersion}" defer></script></head><body><a class="skip" href="#main">انتقل للمحتوى</a><header><a class="brand" href="/"><span class="seal">ش</span><span>ديوان بن شرعان<small>الشاعر / عبدالرحمن بن محمد آل شرعان الخيارين</small></span></a><nav aria-label="التنقل الرئيسي">${[['','الرئيسية'],['index','القصائد']].map(([u,t])=>`<a ${route===u?'aria-current="page"':''} href="/${u}${u?'/':''}">${t}</a>`).join('')}</nav><button class="theme" aria-label="تبديل الوضع الليلي">◐</button></header><main id="main">${content}</main><footer><a class="brand" href="/">ديوان بن شرعان</a><p>جميع الحقوق محفوظة لال شرعان الكرام</p><div><a href="/review/">قائمة المراجعة</a><a href="/source.pdf">المصدر الأصلي</a></div><small>الشاعر / عبدالرحمن بن محمد ال شرعان الخيارين</small></footer><div id="toast" role="status" aria-live="polite"></div></body></html>`;fs.writeFileSync(out,html.replace(/\b(href|src|action)="\/(?!\/)/g,(_,attr)=>`${attr}="${basePath}/`));}
const intro=(label,title,text='')=>`<section class="page-intro"><span class="eyebrow">${label}</span><h1>${title}</h1>${text?`<p>${text}</p>`:''}</section>`;
page('','ديوان بن شرعان','ديوان شعري للشاعر '+poet,`<section class="hero"><div class="quote-panel"><div class="ornament">✧</div><span class="eyebrow">من أبيات الديوان</span><blockquote><span>مكارم الأخلاق من هدي الإسلام</span><span>ياللي تحبون النبي والصحابة</span></blockquote><a href="/poems/p09/">من قصيدة «مكارم الأخلاق» ←</a><div class="ornament bottom">✧</div></div><div class="hero-copy"><span class="eyebrow">الديوان الشعري</span><h1>ديوان <em>بن شرعان</em></h1><p class="poet-name">${poet}</p><p class="hero-desc">بين حكمة القول وصدق الشعور، صفحات من الشعر النبطي تحفظ النص وتقرّبه إلى القارئ.</p><a class="primary" href="/index/">تصفّح الديوان <span>←</span></a></div></section><section class="home-section"><div class="section-head"><div><span class="eyebrow">قراءات مختارة</span><h2>من صفحات الديوان</h2></div><a href="/index/">جميع القصائد ←</a></div><div class="cards">${data.filter(p=>p.featured).sort((a,b)=>(a.featuredOrder??999)-(b.featuredOrder??999)).slice(0,3).map(card).join('')}</div></section>`);
const controls=`<form id="search-form" class="search-box" action="/index/"><label for="query">ابحث في الديوان</label><div class="search-row"><input name="q" id="query" type="search" placeholder="عنوان قصيدة، كلمة، أو شطر..." autocomplete="off"><button class="primary">بحث ←</button></div></form><div class="filters"><label>نطاق البحث <select id="scope"><option value="all">العناوين والأبيات</option><option value="title">العناوين</option><option value="verses">الأبيات</option></select></label></div><p id="result-count" aria-live="polite">${data.length} نصًا في الفهرس</p><div id="results" class="cards">${data.map(card).join('')}</div>`;
page('index','فهرس القصائد','فهرس نصوص الديوان مع البحث ومصدر كل نص',intro('صفحات الديوان','فهرس القصائد','اختر قصيدة، أو ابحث عن الكلمات التي تتذكرها.')+controls);
for(const p of data)page('poems/'+p.id,p.title,`${p.title}، من ديوان بن شرعان`, `<article class="reader"><a class="back" href="/index/">→ فهرس القصائد</a><div class="poem-heading">${badge(p)}<h1>${e(p.title)}</h1><p>${e(p.attribution||poet)}</p><small>${e(p.titleOrigin)} · ${p.source.page&&p.source.region?'صفحة '+p.source.page+'، البطاقة '+p.source.region:p.source.type==='x'?'من فيديو المنشور على X':p.source.type==='user'?'نص أرسله صاحب المشروع':'المصدر لم يوثق بعد'}</small>${p.dedication?`<p class="poem-dedication">${e(p.dedication)}</p>`:''}</div>${p.status.includes('مراجعة')?`<aside class="notice"><strong>يحتاج مراجعة</strong><p>${e((p.issues||[]).join(' · '))}</p></aside>`:''}<div class="reading-tools"><span>خيارات القراءة</span><button id="font-down" aria-label="تصغير الخط">أ−</button><button id="font-up" aria-label="تكبير الخط">أ+</button><button id="share">مشاركة القصيدة ↗</button><button id="copy-link">نسخ الرابط</button></div><div class="verses">${p.verses.map((v,i)=>`<div class="verse" id="verse-${i+1}"><span class="verse-number">${i+1}</span><div class="hemistichs">${v.map(s=>`<span>${e(s)}</span>`).join('')}</div><button class="copy-verse" data-copy="${e(v.join('\n'))}" aria-label="نسخ البيت ${i+1}">نسخ</button></div>`).join('')}</div>${media(p)}<details class="source-panel"><summary>${p.source.type==='x'?'مصدر النص · فيديو على X':p.source.type==='user'?'مصدر النص · صاحب المشروع':'صورة النص في المصدر · البطاقة '+p.source.region}</summary><p>حالة النص: ${e(p.status)}. ${p.source.type==='user'?'حُفظ كما أرسله صاحب المشروع.':'المقابلة البصرية لا تعني اعتمادًا من الشاعر.'}</p>${(p.readingNotes||[]).map(n=>`<p>${e(n)}</p>`).join('')}${p.source.region?`<img loading="lazy" src="/sources/${String(p.source.region).padStart(2,'0')}.png" alt="البطاقة ${p.source.region} كما وردت في صفحة المصدر">`:p.source.type==='x'?`<p>نُقل النص بصريًا من الكتابة داخل فيديو نشره ${e(p.source.publisher)} بتاريخ ${e(p.source.publishedAt)}.</p>`:p.source.type==='user'?`<p>أرسل صاحب المشروع نص القصيدة بتاريخ ${e(p.source.receivedAt)}.</p>`:'<p>أضف مصدر هذا النص قبل اعتماده.</p>'}${p.source.type==='x'?`<a href="${e(p.source.url)}" target="_blank" rel="noopener noreferrer">فتح المنشور المرجعي ↗</a>`:p.source.type==='user'?'':'<a href="/source.pdf">فتح ملف الديوان الأصلي ↗</a>'}</details><a class="back" href="/index/">→ العودة إلى الفهرس</a></article>`);
page('review','قائمة المراجعة','النصوص والكلمات ونسبة الشعر التي تحتاج مراجعة يدوية',intro('حفظ النص يبدأ بتوثيقه','قائمة المراجعة','تظهر هنا المواضع غير المحسومة. يُرجع إلى صورة البطاقة قبل تعديل النص.')+`<div class="review-list">${data.filter(p=>p.status.includes('مراجعة')).map(p=>`<article><span class="tag warn">يحتاج مراجعة</span><h2><a href="${url(p)}">${e(p.title)}</a></h2><p>${p.source.type==='x'?'فيديو المنشور على X':p.source.type==='user'?'نص من صاحب المشروع':'صفحة '+p.source.page+' · البطاقة '+p.source.region}</p><ul>${(p.issues||[]).map(x=>`<li>${e(x)}</li>`).join('')}</ul></article>`).join('')||'<p>لا توجد حاليًا نصوص معلّمة للمراجعة. حُسمت الملاحظات الست بمراجعتها مع صاحب المشروع.</p>'}</div><p class="notice">جميع النصوص المقابلة بصريًا تبقى قابلة للمراجعة التحريرية. لا تُستكمل كلمات غير مقروءة ولا تُصحح اللهجة بصمت.</p>`);
fs.writeFileSync(root+'/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['','index/',...data.map(p=>'poems/'+p.id+'/')].map(r=>`<url><loc>${e(publicUrl(r))}</loc></url>`).join('')}</urlset>`);
fs.writeFileSync(root+'/robots.txt','User-agent: *\nAllow: /\nSitemap: '+origin+basePath+'/sitemap.xml\n');
console.log('Generated',data.length,'poem pages');

}
if(process.argv[1]&&import.meta.url===pathToFileURL(path.resolve(process.argv[1])).href)buildSite();
